{% set version = '1.0.19' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dosnow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/doSNOW_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/doSNOW/doSNOW_{{ version }}.tar.gz
  sha256: 4cd2d080628482f4c6ecab593313d7e42516f5ff13fbf9f90e461fcad0580738

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0
    - r-snow >=0.3.0
  run:
    - r-base
    - r-foreach >=1.2.0
    - r-iterators >=1.0.0
    - r-snow >=0.3.0

test:
  commands:
    - $R -e "library('doSNOW')"           # [not win]
    - "\"%R%\" -e \"library('doSNOW')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/doSNOW/index.html
  license: GPL-2.0-only
  summary: Provides a parallel backend for the %dopar% function using Luke Tierney's snow package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - tomnl
