# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EoM6JIU+dhoowpLA1r6frEWpHZi/KCbMBdDTrumMnP2S9ZZWDFoMr83GPfcy2c8R5oDOX2KIRPFDC4e0mZTiSrvX5VIRnEdKttwedEiDaKoZNIgibmQ62q0HgzclOIHu8he9tlALi+VqmUeYABnf0pVbm0OJdV13H6z+nfd0KbtJgu4jKfiUyT8LxZObHjBgSjhk7d1+DazS+b/WutW9kHNH1ERCbAww+fNVaQLDIi64kUJho7FTvvR54hV8yt8EISjO1Z+5TFnC7KZAARmrRSd0Mg+XclTkm3v2mFsKiQ8O8xop3RExQG3+VB1nzWkIZ0ymLprqkT5KGQUiUezXHTUDQbOHSZGRH52Ment3yWDfI6NVPIeJpWgHVZ2E7n7SmNJ75c/gvzuhx3T+f+2JsAbRD8o3mQTSn9KtRjr/u2HXmuxSUvyarKOVCjorIZPpTa+w/GplSaPFz2tNakyDzG016nWCrg+kNctQgsEVygmeQsAjBdUZbPM1udp4GUygD09WdR6BPXMW7ffddAbnRSr2GiQf/P8hUJlTyZDGo905iabDqI6lM6NqNaWK6wvKsdG5cb9FJgWiUlBun2/wquucZ/dViJUMilTiJt+6kelK8M7xk/W6MQgP91kGcNCuy9p4XjD7K1EocvN/YEsHHVOKfFVR4BXsvYdjswu9VZ0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
